using System;
using System.Collections.Generic;
using System.Text;
using System.IO; 
using ILAutoTestCaseGeneration.TestDefinitions;

namespace ILAutoTestCaseGeneration {
    class Program {
        static void Main(string[] args) {
            string basePath =  Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().CodeBase); 
            basePath = Path.Combine(basePath + Path.DirectorySeparatorChar , @"..\ILNumericsTest\Tests\AutoGenerated\");
            basePath = new Uri(basePath).LocalPath;
            ILTestAutoGenerator generator = new ILTestAutoGenerator(basePath);
            new max_min(generator).Run(); 
            new add(generator).Run(); 
            new subtract(generator).Run(); 
            new multiplyElements(generator).Run(); 
            new divide(generator).Run(); 
        }
    }
}
